#!/usr/bin/env bash

set -euo pipefail
set -x

set +x
. ~/.nvm/nvm.sh
set -x

nvm alias default 24
nvm use default

npm install --no-save --no-audit
npx playwright install --with-deps chromium >/dev/null
