#!/usr/bin/env bash

set -euo pipefail
set -x

set +x
. ~/.nvm/nvm.sh
nvm alias default 24
nvm use default
set -x

npm install --no-save --no-audit
npx playwright install --with-deps chromium >/dev/null
